<a href="https://colab.research.google.com/github/Kishoby/Conceptual-Research_Hybrid-Approach/blob/Multi-Target/MultiTarget_Statistical_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import gc
import warnings

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.api import VAR

warnings.filterwarnings("ignore")

In [2]:
multi_target_df = pd.read_csv("/content/drive/MyDrive/Research v2/Research 18.03.2026/Multi Target/cleaned_multi_target_dataset (1).csv")

print("Dataset shape:", multi_target_df.shape)
multi_target_df.head()

Dataset shape: (130003, 18)

,visibility_km,last_updated_epoch,air_quality_Ozone,latitude,air_quality_PM10,condition_text,air_quality_Sulphur_dioxide,uv_index,air_quality_Nitrogen_dioxide,feels_like_celsius,precip_mm,cloud,pressure_mb,longitude,air_quality_Carbon_Monoxide,air_quality_PM2.5,temperature_celsius,humidity
0,16.0,1715849100,62.2,46.60,7.1,2,0.2,1.0,2.5,16.1,0.00,0,1012.0,-120.49,198.6,6.3,16.1,58
1,10.0,1715849100,23.3,14.10,25.3,32,1.4,1.0,3.7,25.3,0.28,37,1017.0,-87.22,377.2,19.0,23.0,78
2,10.0,1715849100,5.9,13.71,28.1,23,7.5,1.0,7.7,30.2,0.30,50,1010.0,-89.20,460.6,20.4,26.0,94
3,5.0,1715849100,0.4,14.62,178.1,19,19.3,1.0,35.0,20.0,0.09,100,1019.0,-90.53,2243.0,132.0,20.0,88
4,10.0,1715849100,34.0,17.25,32.1,30,0.2,1.0,0.3,29.6,0.00,94,1007.0,-88.77,307.1,7.7,26.0,89

In [3]:
targets = [
    "air_quality_PM2.5",
    "temperature_celsius",
    "humidity"
]

stat_df = multi_target_df[targets].copy()

print("Statistical dataset shape:", stat_df.shape)
stat_df.head()

Statistical dataset shape: (130003, 3)

   air_quality_PM2.5  temperature_celsius  humidity
0                6.3                 16.1        58
1               19.0                 23.0        78
2               20.4                 26.0        94
3              132.0                 20.0        88
4                7.7                 26.0        89

In [4]:
split_index = int(0.8 * len(stat_df))

train_df = stat_df.iloc[:split_index].copy()
test_df = stat_df.iloc[split_index:].copy()

print("Train shape:", train_df.shape)
print("Test shape :", test_df.shape)

Train shape: (104002, 3)
Test shape : (26001, 3)

In [5]:
def calculate_metrics_series(y_true, y_pred, model_name, dataset_type, target_name):
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    acc = r2 * 100

    return pd.DataFrame([[
        dataset_type,
        model_name,
        target_name,
        mse,
        rmse,
        mae,
        r2,
        acc
    ]], columns=["Dataset", "Model", "Target", "MSE", "RMSE", "MAE", "R2", "Accuracy (%)"]).round(3)

In [6]:
arima_training_results = []
arima_testing_results = []

for target in targets:
    print(f"\nRunning ARIMA for {target}")

    train_series = train_df[target]
    test_series = test_df[target]

    # light ARIMA
    arima_model = ARIMA(
        train_series,
        order=(1, 1, 1)
    )
    arima_fit = arima_model.fit()

    # training prediction
    train_pred = arima_fit.predict(start=1, end=len(train_series) - 1)
    train_actual = train_series.iloc[1:]

    arima_training_results.append(
        calculate_metrics_series(
            train_actual,
            train_pred,
            model_name="ARIMA",
            dataset_type="Training",
            target_name=target
        )
    )

    # testing forecast
    test_pred = arima_fit.forecast(steps=len(test_series))

    arima_testing_results.append(
        calculate_metrics_series(
            test_series,
            test_pred,
            model_name="ARIMA",
            dataset_type="Testing",
            target_name=target
        )
    )

    del arima_model, arima_fit, train_pred, test_pred
    gc.collect()

Running ARIMA for air_quality_PM2.5

Running ARIMA for temperature_celsius

Running ARIMA for humidity

In [7]:
arima_training_table = pd.concat(arima_training_results, ignore_index=True)
arima_testing_table = pd.concat(arima_testing_results, ignore_index=True)

print("ARIMA TRAINING RESULTS")
display(arima_training_table)

print("ARIMA TESTING RESULTS")
display(arima_testing_table)

ARIMA TRAINING RESULTS

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Training,ARIMA,air_quality_PM2.5,1543.698,39.290,19.623,0.031,3.086
1,Training,ARIMA,temperature_celsius,64.727,8.045,6.242,0.174,17.351
2,Training,ARIMA,humidity,405.115,20.127,15.781,0.306,30.550

ARIMA TESTING RESULTS

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Testing,ARIMA,air_quality_PM2.5,610.825,24.715,13.870,-0.020,-2.025
1,Testing,ARIMA,temperature_celsius,155.339,12.464,9.273,-0.251,-25.074
2,Testing,ARIMA,humidity,741.477,27.230,24.380,-0.547,-54.673

In [8]:
sarima_training_results = []
sarima_testing_results = []

seasonal_period = 12   # keep as 12 unless you know a better seasonal cycle

for target in targets:
    print(f"\nRunning SARIMA for {target}")

    train_series = train_df[target]
    test_series = test_df[target]

    sarima_model = SARIMAX(
        train_series,
        order=(1, 1, 0),
        seasonal_order=(0, 1, 1, seasonal_period),
        trend="n",
        simple_differencing=True,
        enforce_stationarity=False,
        enforce_invertibility=False
    )

    sarima_fit = sarima_model.fit(
        disp=False,
        maxiter=30
    )

    # training prediction
    start_idx = seasonal_period
    train_pred = sarima_fit.predict(start=start_idx, end=len(train_series) - 1)
    train_actual = train_series.iloc[start_idx:]

    sarima_training_results.append(
        calculate_metrics_series(
            train_actual,
            train_pred,
            model_name="SARIMA",
            dataset_type="Training",
            target_name=target
        )
    )

    # testing forecast
    test_pred = sarima_fit.forecast(steps=len(test_series))

    sarima_testing_results.append(
        calculate_metrics_series(
            test_series,
            test_pred,
            model_name="SARIMA",
            dataset_type="Testing",
            target_name=target
        )
    )

    del sarima_model, sarima_fit, train_pred, test_pred
    gc.collect()

Running SARIMA for air_quality_PM2.5

Running SARIMA for temperature_celsius

Running SARIMA for humidity

In [9]:
sarima_training_table = pd.concat(sarima_training_results, ignore_index=True)
sarima_testing_table = pd.concat(sarima_testing_results, ignore_index=True)

print("SARIMA TRAINING RESULTS")
display(sarima_training_table)

print("SARIMA TESTING RESULTS")
display(sarima_testing_table)

SARIMA TRAINING RESULTS

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Training,SARIMA,air_quality_PM2.5,2975.325,54.547,30.603,-0.868,-86.788
1,Training,SARIMA,temperature_celsius,619.795,24.896,23.003,-6.913,-691.348
2,Training,SARIMA,humidity,4918.468,70.132,64.826,-7.432,-743.188

SARIMA TESTING RESULTS

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Testing,SARIMA,air_quality_PM2.5,1004.770,31.698,20.149,-0.678,-67.824
1,Testing,SARIMA,temperature_celsius,391.812,19.794,17.421,-2.155,-215.475
2,Testing,SARIMA,humidity,5899.506,76.808,73.620,-11.306,-1130.643

In [10]:
var_model = VAR(train_df)

lag_selection = var_model.select_order(maxlags=8)
print(lag_selection.summary())

best_lag = lag_selection.aic
print("Best lag by AIC:", best_lag)

# fallback if AIC returns None
if best_lag is None:
    best_lag = 2

var_fit = var_model.fit(best_lag)
print(var_fit.summary())

 VAR Order Selection (* highlights the minimums)
=================================================
      AIC         BIC         FPE         HQIC
-------------------------------------------------
0       17.94       17.94   6.179e+07       17.94
1       17.68       17.68   4.776e+07       17.68
2       17.56       17.56   4.231e+07       17.56
3       17.49       17.50   3.955e+07       17.49
4       17.45       17.45   3.770e+07       17.45
5       17.41       17.41   3.640e+07       17.41
6       17.38       17.39   3.546e+07       17.39
7       17.37       17.37   3.492e+07       17.37
8      17.36*      17.36*  3.447e+07*      17.36*
-------------------------------------------------
Best lag by AIC: 8
  Summary of Regression Results
==================================
Model:                         VAR
Method:                        OLS
Date:           Tue, 31, Mar, 2026
Time:                     06:37:35
--------------------------------------------------------------------
No. of Equations:         3.00000    BIC:                    17.3626
Nobs:                     103994.    HQIC:                   17.3578
Log likelihood:      -1.34505e+06    FPE:                3.44747e+07
AIC:                      17.3557    Det(Omega_mle):     3.44499e+07
--------------------------------------------------------------------
Results for equation air_quality_PM2.5
=========================================================================================
                            coefficient       std. error           t-stat            prob
-----------------------------------------------------------------------------------------
const                         29.738110         0.966975           30.754           0.000
L1.air_quality_PM2.5           0.049764         0.003158           15.756           0.000
L1.temperature_celsius         0.027103         0.015993            1.695           0.090
L1.humidity                    0.010949         0.006528            1.677           0.094
L2.air_quality_PM2.5           0.052278         0.003160           16.542           0.000
L2.temperature_celsius         0.004855         0.016094            0.302           0.763
L2.humidity                    0.006094         0.006593            0.924           0.355
L3.air_quality_PM2.5           0.053029         0.003161           16.776           0.000
L3.temperature_celsius        -0.040700         0.016129           -2.523           0.012
L3.humidity                   -0.022002         0.006617           -3.325           0.001
L4.air_quality_PM2.5           0.050929         0.003162           16.107           0.000
L4.temperature_celsius        -0.053085         0.016130           -3.291           0.001
L4.humidity                   -0.008831         0.006622           -1.334           0.182
L5.air_quality_PM2.5           0.048082         0.003162           15.206           0.000
L5.temperature_celsius        -0.056543         0.016130           -3.505           0.000
L5.humidity                   -0.017051         0.006622           -2.575           0.010
L6.air_quality_PM2.5           0.047778         0.003161           15.113           0.000
L6.temperature_celsius        -0.062226         0.016131           -3.857           0.000
L6.humidity                   -0.021213         0.006619           -3.205           0.001
L7.air_quality_PM2.5           0.041695         0.003161           13.190           0.000
L7.temperature_celsius        -0.096546         0.016100           -5.997           0.000
L7.humidity                   -0.040053         0.006597           -6.071           0.000
L8.air_quality_PM2.5           0.042641         0.003159           13.496           0.000
L8.temperature_celsius        -0.054280         0.016005           -3.392           0.001
L8.humidity                   -0.009247         0.006537           -1.415           0.157
=========================================================================================

Results for equation temperature_celsius
=========================================================================================
                            coefficient       std. error           t-stat            prob
-----------------------------------------------------------------------------------------
const                          9.531638         0.199404           47.801           0.000
L1.air_quality_PM2.5          -0.002014         0.000651           -3.093           0.002
L1.temperature_celsius         0.123326         0.003298           37.393           0.000
L1.humidity                   -0.000287         0.001346           -0.213           0.831
L2.air_quality_PM2.5          -0.001985         0.000652           -3.046           0.002
L2.temperature_celsius         0.101484         0.003319           30.579           0.000
L2.humidity                   -0.000744         0.001360           -0.548           0.584
L3.air_quality_PM2.5          -0.001924         0.000652           -2.951           0.003
L3.temperature_celsius         0.078690         0.003326           23.658           0.000
L3.humidity                   -0.002008         0.001365           -1.472           0.141
L4.air_quality_PM2.5          -0.003716         0.000652           -5.700           0.000
L4.temperature_celsius         0.077571         0.003326           23.320           0.000
L4.humidity                   -0.004724         0.001365           -3.460           0.001
L5.air_quality_PM2.5          -0.001643         0.000652           -2.520           0.012
L5.temperature_celsius         0.081602         0.003326           24.533           0.000
L5.humidity                    0.000483         0.001366            0.354           0.723
L6.air_quality_PM2.5          -0.001920         0.000652           -2.945           0.003
L6.temperature_celsius         0.077934         0.003327           23.428           0.000
L6.humidity                   -0.002818         0.001365           -2.064           0.039
L7.air_quality_PM2.5          -0.002935         0.000652           -4.502           0.000
L7.temperature_celsius         0.061585         0.003320           18.550           0.000
L7.humidity                   -0.007708         0.001360           -5.666           0.000
L8.air_quality_PM2.5          -0.001937         0.000652           -2.973           0.003
L8.temperature_celsius         0.062615         0.003300           18.972           0.000
L8.humidity                   -0.004983         0.001348           -3.697           0.000
=========================================================================================

Results for equation humidity
=========================================================================================
                            coefficient       std. error           t-stat            prob
-----------------------------------------------------------------------------------------
const                          5.367331         0.496514           10.810           0.000
L1.air_quality_PM2.5           0.012374         0.001622            7.630           0.000
L1.temperature_celsius         0.038498         0.008212            4.688           0.000
L1.humidity                    0.154685         0.003352           46.147           0.000
L2.air_quality_PM2.5           0.006706         0.001623            4.133           0.000
L2.temperature_celsius         0.025201         0.008264            3.050           0.002
L2.humidity                    0.124735         0.003385           36.847           0.000
L3.air_quality_PM2.5           0.002346         0.001623            1.445           0.148
L3.temperature_celsius         0.023337         0.008282            2.818           0.005
L3.humidity                    0.105875         0.003398           31.161           0.000
L4.air_quality_PM2.5           0.002922         0.001624            1.800           0.072
L4.temperature_celsius         0.018635         0.008283            2.250           0.024
L4.humidity                    0.102023         0.003400           30.007           0.000
L5.air_quality_PM2.5           0.003066         0.001624            1.888           0.059
L5.temperature_celsius         0.002138         0.008282            0.258           0.796
L5.humidity                    0.096921         0.003400           28.503           0.000
L6.air_quality_PM2.5           0.008123         0.001623            5.004           0.000
L6.temperature_celsius         0.025568         0.008283            3.087           0.002
L6.humidity                    0.094350         0.003399           27.760           0.000
L7.air_quality_PM2.5           0.005843         0.001623            3.600           0.000
L7.temperature_celsius         0.014598         0.008267            1.766           0.077
L7.humidity                    0.076404         0.003387           22.556           0.000
L8.air_quality_PM2.5           0.004057         0.001622            2.501           0.012
L8.temperature_celsius         0.023488         0.008218            2.858           0.004
L8.humidity                    0.083790         0.003356           24.964           0.000
=========================================================================================

Correlation matrix of residuals
                       air_quality_PM2.5  temperature_celsius  humidity
air_quality_PM2.5               1.000000             0.065053 -0.194344
temperature_celsius             0.065053             1.000000 -0.345911
humidity                       -0.194344            -0.345911  1.000000

In [11]:
var_train_pred = var_fit.fittedvalues.copy()
var_train_actual = train_df.iloc[best_lag:].copy()

print("VAR train actual shape:", var_train_actual.shape)
print("VAR train predicted shape:", var_train_pred.shape)

VAR train actual shape: (103994, 3)
VAR train predicted shape: (103994, 3)

In [12]:
var_training_results = []

for target in targets:
    var_training_results.append(
        calculate_metrics_series(
            var_train_actual[target],
            var_train_pred[target],
            model_name="VAR",
            dataset_type="Training",
            target_name=target
        )
    )

var_training_table = pd.concat(var_training_results, ignore_index=True)

print("VAR TRAINING RESULTS")
display(var_training_table)

VAR TRAINING RESULTS

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Training,VAR,air_quality_PM2.5,1536.118,39.193,19.494,0.036,3.561
1,Training,VAR,temperature_celsius,65.322,8.082,6.293,0.166,16.595
2,Training,VAR,humidity,405.002,20.125,15.900,0.306,30.570

In [13]:
forecast_input = train_df.values[-best_lag:]
forecast_steps = len(test_df)

var_forecast = var_fit.forecast(y=forecast_input, steps=forecast_steps)
var_test_pred = pd.DataFrame(var_forecast, columns=targets, index=test_df.index)

print("VAR test prediction shape:", var_test_pred.shape)
var_test_pred.head()

VAR test prediction shape: (26001, 3)

        air_quality_PM2.5  temperature_celsius   humidity
104002          25.200068            23.945245  52.873411
104003          24.424608            23.800498  55.943107
104004          23.256579            23.562491  57.146244
104005          23.842908            23.589666  60.339159
104006          23.533432            23.176920  60.535882

In [14]:
var_testing_results = []

for target in targets:
    var_testing_results.append(
        calculate_metrics_series(
            test_df[target],
            var_test_pred[target],
            model_name="VAR",
            dataset_type="Testing",
            target_name=target
        )
    )

var_testing_table = pd.concat(var_testing_results, ignore_index=True)

print("VAR TESTING RESULTS")
display(var_testing_table)

VAR TESTING RESULTS

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Testing,VAR,air_quality_PM2.5,627.852,25.057,17.362,-0.049,-4.869
1,Testing,VAR,temperature_celsius,164.014,12.807,9.416,-0.321,-32.059
2,Testing,VAR,humidity,560.635,23.678,20.612,-0.169,-16.949

In [15]:
training_table = pd.concat([
    arima_training_table,
    sarima_training_table,
    var_training_table
], ignore_index=True)

print("FINAL TRAINING TABLE")
display(training_table)

FINAL TRAINING TABLE

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Training,ARIMA,air_quality_PM2.5,1543.698,39.290,19.623,0.031,3.086
1,Training,ARIMA,temperature_celsius,64.727,8.045,6.242,0.174,17.351
2,Training,ARIMA,humidity,405.115,20.127,15.781,0.306,30.550
3,Training,SARIMA,air_quality_PM2.5,2975.325,54.547,30.603,-0.868,-86.788
4,Training,SARIMA,temperature_celsius,619.795,24.896,23.003,-6.913,-691.348
5,Training,SARIMA,humidity,4918.468,70.132,64.826,-7.432,-743.188
6,Training,VAR,air_quality_PM2.5,1536.118,39.193,19.494,0.036,3.561
7,Training,VAR,temperature_celsius,65.322,8.082,6.293,0.166,16.595
8,Training,VAR,humidity,405.002,20.125,15.900,0.306,30.570

In [16]:
testing_table = pd.concat([
    arima_testing_table,
    sarima_testing_table,
    var_testing_table
], ignore_index=True)

print("FINAL TESTING TABLE")
display(testing_table)

FINAL TESTING TABLE

,Dataset,Model,Target,MSE,RMSE,MAE,R2,Accuracy (%)
0,Testing,ARIMA,air_quality_PM2.5,610.825,24.715,13.870,-0.020,-2.025
1,Testing,ARIMA,temperature_celsius,155.339,12.464,9.273,-0.251,-25.074
2,Testing,ARIMA,humidity,741.477,27.230,24.380,-0.547,-54.673
3,Testing,SARIMA,air_quality_PM2.5,1004.770,31.698,20.149,-0.678,-67.824
4,Testing,SARIMA,temperature_celsius,391.812,19.794,17.421,-2.155,-215.475
5,Testing,SARIMA,humidity,5899.506,76.808,73.620,-11.306,-1130.643
6,Testing,VAR,air_quality_PM2.5,627.852,25.057,17.362,-0.049,-4.869
7,Testing,VAR,temperature_celsius,164.014,12.807,9.416,-0.321,-32.059
8,Testing,VAR,humidity,560.635,23.678,20.612,-0.169,-16.949

In [17]:
from google.colab import files

training_table.to_csv("statistical_models_training_results.csv", index=False)
testing_table.to_csv("statistical_models_testing_results.csv", index=False)

files.download("statistical_models_training_results.csv")
files.download("statistical_models_testing_results.csv")